# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Kmeans <- function(X, M, MaxIter) {
    .Call(`_acpc_Kmeans`, X, M, MaxIter)
}

robustPCA <- function(M, eps, MaxIter, gamma, tau) {
    .Call(`_acpc_robustPCA`, M, eps, MaxIter, gamma, tau)
}

sparsePCA <- function(X, eps, MaxIter, r, lambda) {
    .Call(`_acpc_sparsePCA`, X, eps, MaxIter, r, lambda)
}

