# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LRMultiClass_c <- function(X_ext, X, y, numIter, eta = 0.1, lambda = 1) {
    .Call(`_acpc_LRMultiClass_c`, X_ext, X, y, numIter, eta, lambda)
}

MyKmeans_c <- function(X, K, M, numIter) {
    .Call(`_acpc_MyKmeans_c`, X, K, M, numIter)
}

procrustes <- function(X, V) {
    .Call(`_acpc_procrustes`, X, V)
}

soft_I <- function(a, lambda) {
    .Call(`_acpc_soft_I`, a, lambda)
}

sparsePCA <- function(X, r, lambda, eps) {
    .Call(`_acpc_sparsePCA`, X, r, lambda, eps)
}

